# Generated by Django 5.2.7 on 2025-10-31 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionInforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ejecucion', models.CharField(choices=[('manual', 'Manual'), ('automatica', 'Automática')], default='manual', max_length=50)),
                ('archivo_qps', models.FileField(blank=True, null=True, upload_to='qps/')),
                ('carpeta_qps', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('encargado', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('archivo_xlsx', models.FileField(blank=True, null=True, upload_to='informes/xlsx/')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='informes/pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_pressure', models.FloatField(blank=True, null=True)),
                ('volume_stp', models.FloatField(blank=True, null=True)),
                ('inv_w_po', models.FloatField(blank=True, null=True)),
                ('slope', models.FloatField(blank=True, null=True)),
                ('surf_area', models.FloatField(blank=True, null=True)),
                ('radius_area', models.FloatField(blank=True, null=True)),
                ('pore_volume', models.FloatField(blank=True, null=True)),
                ('pore_surf', models.FloatField(blank=True, null=True)),
                ('dv_r', models.FloatField(blank=True, null=True)),
                ('ds_r', models.FloatField(blank=True, null=True)),
                ('dv_logr', models.FloatField(blank=True, null=True)),
                ('ds_logr', models.FloatField(blank=True, null=True)),
                ('half_pore_width', models.FloatField(blank=True, null=True)),
                ('cumulative_volume', models.FloatField(blank=True, null=True)),
                ('cumulative_surface_area', models.FloatField(blank=True, null=True)),
                ('radius_of_curvature', models.FloatField(blank=True, null=True)),
                ('vapor_liquid_area', models.FloatField(blank=True, null=True)),
                ('log_log_po', models.FloatField(blank=True, null=True)),
                ('log_vads', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muestras_crud.informe')),
            ],
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_number', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muestras_crud.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='informe',
            name='muestra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muestras_crud.muestra'),
        ),
    ]
