# Generated by Django 5.2.7 on 2025-10-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras_crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='cell',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='informe',
            name='multiBET',
            field=models.FloatField(default=0),
        ),
    ]
