# Generated by Django 5.2.7 on 2025-10-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras_crud', '0002_informe_cell_informe_multibet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='cell',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='informe',
            name='multiBET',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
