# Generated by Django 5.2.7 on 2025-10-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras_crud', '0003_alter_informe_cell_alter_informe_multibet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='cell',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Cell'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='multiBET',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='MultiBET'),
        ),
    ]
