# Generated by Django 3.2.25 on 2026-01-05 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muestras_crud', '0014_rename_bet_average_a_dataset_bottle_ink_valor_clave_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informe',
            name='cell',
        ),
        migrations.RemoveField(
            model_name='informe',
            name='multiBET',
        ),
    ]
