# Generated by Django 3.2.25 on 2026-01-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras_crud', '0015_auto_20260105_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='bet_surf_area',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='bjh_pore_volume',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='bjh_volume_average',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='bottle_ink_valor_clave',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='cylindrical_valor_clave',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='fhh_radius_of_curvature',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='nka_radius_of_curvature',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='plate_valor_clave',
        ),
        migrations.AddField(
            model_name='dataset',
            name='bjh_pore_volume_avg',
            field=models.FloatField(blank=True, help_text='Promedio del volumen acumulado BJHA y BJHD (cc/g)', null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='dft_half_pore_width',
            field=models.FloatField(blank=True, help_text='Half Pore Width (DFT)', null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='fractal_fhh',
            field=models.FloatField(blank=True, help_text='Número fractal FHH', null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='fractal_nk',
            field=models.FloatField(blank=True, help_text='Número fractal NK', null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='single_bet',
            field=models.FloatField(blank=True, help_text='Área superficial BET (Single BET)', null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='total_pore_volume',
            field=models.FloatField(blank=True, help_text='Volumen total de poros (cc/g)', null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dft_pore_volume',
            field=models.FloatField(blank=True, help_text='Pore Volume DFT (cc/g)', null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='hk_volume_cc_g',
            field=models.FloatField(blank=True, help_text='Último valor acumulado HK Volume (cc/g)', null=True),
        ),
    ]
