# Generated by Django 3.2.25 on 2026-01-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras_crud', '0016_auto_20260105_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='total_pore_volume',
        ),
        migrations.AddField(
            model_name='dataset',
            name='desviacion_estandar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='vol_mesoporos_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='vol_mesoporos_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='vol_microporos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='bjh_pore_volume_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dft_half_pore_width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dft_pore_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='fractal_fhh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='fractal_nk',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='hk_volume_cc_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='single_bet',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
