# Generated by Django 3.2.25 on 2026-01-05 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muestras_crud', '0017_auto_20260105_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='desviacion_estandar',
            new_name='fhh',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='fractal_fhh',
            new_name='nk',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='fractal_nk',
        ),
    ]
