# Generated by Django 3.2.25 on 2026-01-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras_crud', '0018_auto_20260105_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
