# Generated by Django 3.2.25 on 2026-01-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras_crud', '0019_alter_informe_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='vol_mesoporos_1',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='vol_mesoporos_2',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='vol_microporos',
        ),
        migrations.AddField(
            model_name='dataset',
            name='volumen_total_porosidad',
            field=models.FloatField(blank=True, null=True, verbose_name='Volumen total de porosidad (cc/g)'),
        ),
    ]
